# Pipeline de Datos — CRM + Billing + Universidad

## 1. Objetivo del proyecto

Construir, de extremo a extremo, un pipeline de datos que transforme los CSV crudos
de tres sistemas de origen distintos (CRM, Billing y Universidad), que en conjunto
describen el mismo negocio (una institución que ofrece cursos y factura
suscripciones), en información confiable para el negocio, siguiendo una
arquitectura medallion (Bronze a Silver a Gold) sobre PostgreSQL, con Python/SQL
como motor de transformación y Jupyter como espacio de discovery y validación.

## 2. Descripción de las fuentes de datos

Tres dominios, 18 archivos CSV, cargados sin transformar en `bronze.*` por
`src/ingest/load_raw_bronze.py` (fase de ingesta). El esquema completo (columnas y
filas esperadas) está en `manifest.json`.

In [13]:
import json
import os
from pathlib import Path
import pandas as pd
from sqlalchemy import create_engine, text


def find_project_root(current_dir: Path) -> Path:
    for parent in [current_dir] + list(current_dir.parents):
        if (parent / "manifest.json").exists():
            return parent
    raise FileNotFoundError("No se encontró el archivo manifest.json en ningún directorio padre.")

PROJECT_ROOT = find_project_root(Path.cwd())
manifest = json.loads((PROJECT_ROOT / "manifest.json").read_text())
rows = []

for domain, tables in manifest["domains"].items():
    for table, meta in tables.items():
        rows.append({
            "dominio": domain, 
            "tabla": table, 
            "filas_esperadas": meta["rows"], 
            "columnas": len(meta["cols"])
        })

df_manifest = pd.DataFrame(rows)
df_manifest

       dominio                 tabla  filas_esperadas  columnas
0   university             semesters                8         6
1   university            professors              200         6
2   university              students             5000         7
3   university               courses              300         6
4   university           enrollments            25000         6
5   university                grades            60000         6
6      billing             customers            10000         8
7      billing              products              200         6
8      billing         subscriptions            15000         6
9      billing              invoices            50000         7
10     billing         invoice_items           150000         6
11     billing              payments            80000         5
12         crm              accounts             5000         7
13         crm              contacts            15000         8
14         crm                 leads             2000         8
15         crm         opportunities             3000         7
16         crm  opportunity_contacts             6000         3
17         crm            activities            20000         6

In [19]:
user = os.environ.get("WAREHOUSE_DB_USER", "postgres")
password = os.environ.get("WAREHOUSE_DB_PASSWORD", "postgres")
db = os.environ.get("WAREHOUSE_DB_NAME", "warehouse")
host = os.environ.get("WAREHOUSE_DB_HOST", "warehouse-db")
port = os.environ.get("WAREHOUSE_DB_PORT", "5432")

In [20]:
engine = create_engine(f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db}")

In [21]:
#Comparación de filas cargadas en bronze con manifest
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'bronze'
ORDER BY table_name;
"""
bronze_tables = pd.read_sql(query, engine)["table_name"].tolist()

counts = []
for t in bronze_tables:
    n = pd.read_sql(f"SELECT COUNT(*) AS n FROM bronze.{t}", engine)["n"].iloc[0]
    counts.append({"tabla_bronze": t, "filas": n})

df_bronze_counts = pd.DataFrame(counts)
df_bronze_counts

                tabla_bronze   filas
0          billing_customers   10000
1      billing_invoice_items  150000
2           billing_invoices   50000
3           billing_payments   80000
4           billing_products     200
5      billing_subscriptions   15000
6               crm_accounts    5000
7             crm_activities   20000
8               crm_contacts   15000
9                  crm_leads    2000
10         crm_opportunities    3000
11  crm_opportunity_contacts    6000
12        university_courses     300
13    university_enrollments   25000
14         university_grades   60000
15     university_professors     200
16      university_semesters       8
17       university_students    5000

## 3. Data Profiling

El perfilado exhaustivo (nulos, duplicados, cardinalidades, tipos, distribuciones)
por tabla se hizo en `notebooks/discovery_university.ipynb`,
`notebooks/discovery_billing.ipynb` y `notebooks/discovery_crm.ipynb`, y sus
hallazgos están consolidados en `docs/decisiones.md` (secciones 1 y 2). Aquí se
verifican en vivo los números clave que sustentan las decisiones de limpieza de la
sección 4.

In [16]:
# Nulos: solo 2 columnas presentan nulos en todo el dataset (por diseño, no por defecto)
query = """
SELECT
  COUNT(*) AS total_activities,
  COUNT(*) FILTER (WHERE contact_id IS NULL) AS contact_id_nulo,
  COUNT(*) FILTER (WHERE opportunity_id IS NULL) AS opportunity_id_nulo
FROM bronze.crm_activities;
"""
pd.read_sql(query, engine)

   total_activities  contact_id_nulo  opportunity_id_nulo
0             20000             5976                 9985

In [23]:
# Duplicados por (enrollment_id, assessment) en university_grades
query = """
SELECT n, COUNT(*) AS n_grupos
FROM (
  SELECT enrollment_id, assessment, COUNT(*) AS n
  FROM bronze.university_grades
  GROUP BY enrollment_id, assessment
) t
GROUP BY n
ORDER BY n;
"""
pd.read_sql(query, engine)

   n  n_grupos
0  1     37133
1  2      8954
2  3      1417
3  4       158
4  5        14
5  6         1

## 4. Limpieza y transformaciones realizadas (Silver)

Política general (justificada en `docs/decisiones.md` §3): **no se elimina ni se
"corrige" ninguna fila** por inconsistencia cronológica o de negocio — se tipa,
se estandariza, y se marca con columnas `_dq_*`. Deduplicación solo donde la
evidencia confirma redundancia real de la misma entidad (`university_grades`).

La construcción corre en SQL (`sql/silver/silver_university.sql`,
`silver_billing.sql`, `silver_crm.sql`), no en pandas — es lo que exige el stack del
proyecto ("SQL: modelado y transformaciones de negocio") y mantiene consistencia con
cómo se implementó Bronze (`src/ingest/load_raw_bronze.py`). El notebook solo
ejecuta y valida, no transforma.

In [33]:
import subprocess

result = subprocess.run(
    ["python3", str(PROJECT_ROOT / "src" / "transform" / "build_silver.py")],
    capture_output=True,
    text=True,
    env=os.environ,
)
print(result.stdout[-2000:])
if result.returncode != 0:
    print(result.stderr)
assert result.returncode == 0

======================================================================
SILVER BUILD
======================================================================
======================================================================
Ejecutando: silver_university.sql
======================================================================
Ejecutando: silver_billing.sql
======================================================================
Ejecutando: silver_crm.sql


======================================================================
Conteo de filas por tabla silver:
======================================================================
  silver.billing_customers                10,000
  silver.billing_invoice_items           150,000
  silver.billing_invoices                 50,000
  silver.billing_payments                 80,000
  silver.billing_products                    200
  silver.billing_subscriptions            15,000
  silver.crm_accounts                      5,000
  silver.crm_activities                   20,000
  silver.crm_contacts                     15,000
  silver.crm_leads                         2,000
  silver.crm_opportunities                 3,000
  silver.crm_opportunity_contacts          6,000
  silver.university_courses                  300
  silver.university_enrollments           25,000
  silver.university_grades                47,677
  silver.university_professors               200
  silver.university_semesters                  8
  silver.university_students               5,000


======================================================================
Construcción Silver finalizada correctamente.
======================================================================

In [35]:
# Conteo de filas y coincidencia 1:1, excepto university_grades (deduplicada)
query = """
SELECT table_name FROM information_schema.tables WHERE table_schema = 'silver' ORDER BY table_name;
"""
silver_tables = pd.read_sql(query, engine)["table_name"].tolist()

comparison = []
for t in silver_tables:
    b = pd.read_sql(f"SELECT COUNT(*) AS n FROM bronze.{t}", engine)["n"].iloc[0]
    s = pd.read_sql(f"SELECT COUNT(*) AS n FROM silver.{t}", engine)["n"].iloc[0]
    comparison.append({"tabla": t, "filas_bronze": b, "filas_silver": s, "diferencia": b - s})

df_comparison = pd.DataFrame(comparison)
df_comparison

                       tabla  filas_bronze  filas_silver  diferencia
0          billing_customers         10000         10000           0
1      billing_invoice_items        150000        150000           0
2           billing_invoices         50000         50000           0
3           billing_payments         80000         80000           0
4           billing_products           200           200           0
5      billing_subscriptions         15000         15000           0
6               crm_accounts          5000          5000           0
7             crm_activities         20000         20000           0
8               crm_contacts         15000         15000           0
9                  crm_leads          2000          2000           0
10         crm_opportunities          3000          3000           0
11  crm_opportunity_contacts          6000          6000           0
12        university_courses           300           300           0
13    university_enrollments         25000         25000           0
14         university_grades         60000         47677       12323
15     university_professors           200           200           0
16      university_semesters             8             8           0
17       university_students          5000          5000           0

## 5. Análisis de relaciones entre dominios y justificación

Verificación en vivo de los tres hallazgos de relación documentados en
`docs/decisiones.md` §1.

In [36]:
# university <-> billing: billing.customers.external_ref vs university.students.student_id
query = """
SELECT
  COUNT(*) AS con_external_ref,
  COUNT(s.student_id) AS con_match_en_university,
  COUNT(*) FILTER (WHERE s.country IS NOT NULL AND s.country <> c.country) AS pais_distinto
FROM silver.billing_customers c
LEFT JOIN silver.university_students s ON s.student_id = c.external_ref
WHERE c.external_ref IS NOT NULL;
"""
pd.read_sql(query, engine)

   con_external_ref  con_match_en_university  pais_distinto
0              5000                     5000           3928

In [37]:
# crm <-> billing: no hay join explotable por email
query = """
SELECT
  COUNT(*) AS total_contacts,
  COUNT(c.customer_id) AS con_match_en_billing
FROM silver.crm_contacts ct
LEFT JOIN silver.billing_customers c ON c.email = ct.email;
"""
pd.read_sql(query, engine)

   total_contacts  con_match_en_billing
0           15000                     1

In [38]:
# crm.leads: tabla aislada, sin conversion reconstruible hacia contacts
query = """
SELECT
  COUNT(*) AS total_leads,
  COUNT(ct.contact_id) AS con_match_en_contacts
FROM silver.crm_leads l
LEFT JOIN silver.crm_contacts ct ON ct.email = l.email;
"""
pd.read_sql(query, engine)

   total_leads  con_match_en_contacts
0         2000                      0

## 6. Implementación del pipeline Bronze → Silver: validación de reglas de calidad

Cada columna `_dq_*` marca, sin eliminar la fila, una violación de una regla de
negocio detectada en Bronze (detalle y justificación por tabla en
`docs/decisiones.md` §2.5, §2.6 y §4). Se valida aquí que los conteos coinciden con
lo documentado.

In [39]:
dq_checks = [
    ("silver.university_courses", "_dq_professor_dept_mismatch"),
    ("silver.university_students", "_dq_enrolled_after_first_course"),
    ("silver.university_enrollments", "_dq_outside_semester_range"),
    ("silver.university_grades", "_dq_graded_before_enrollment"),
    ("silver.university_grades", "_dq_graded_after_semester_end"),
    ("silver.billing_customers", "_dq_country_mismatch_university"),
    ("silver.billing_subscriptions", "_dq_start_after_end"),
    ("silver.billing_invoices", "_dq_total_mismatch_items"),
    ("silver.crm_contacts", "_dq_created_before_account"),
    ("silver.crm_opportunities", "_dq_close_before_created"),
    ("silver.crm_activities", "_dq_occurred_before_contact"),
    ("silver.crm_activities", "_dq_occurred_before_opportunity"),
]

rows = []
for table, flag in dq_checks:
    query = f"""
        SELECT COUNT(*) FILTER (WHERE {flag}) AS n_marcadas, COUNT(*) AS total
        FROM {table};
    """
    r = pd.read_sql(query, engine).iloc[0]
    rows.append({
        "tabla": table,
        "flag": flag,
        "filas_marcadas": int(r["n_marcadas"]),
        "total_filas": int(r["total"]),
        "pct": round(100 * r["n_marcadas"] / r["total"], 1),
    })

df_dq = pd.DataFrame(rows)
df_dq

,tabla,flag,filas_marcadas,total_filas,pct
0,silver.university_courses,_dq_professor_dept_mismatch,264,300,88.0
1,silver.university_students,_dq_enrolled_after_first_course,1851,5000,37.0
2,silver.university_enrollments,_dq_outside_semester_range,22729,25000,90.9
3,silver.university_grades,_dq_graded_before_enrollment,21386,47677,44.9
4,silver.university_grades,_dq_graded_after_semester_end,23141,47677,48.5
5,silver.billing_customers,_dq_country_mismatch_university,3928,10000,39.3
6,silver.billing_subscriptions,_dq_start_after_end,789,15000,5.3
7,silver.billing_invoices,_dq_total_mismatch_items,49999,50000,100.0
8,silver.crm_contacts,_dq_created_before_account,7456,15000,49.7
9,silver.crm_opportunities,_dq_close_before_created,1029,3000,34.3
10,silver.crm_activities,_dq_occurred_before_contact,2579,20000,12.9
11,silver.crm_activities,_dq_occurred_before_opportunity,3792,20000,19.0